name: Build Dataverse Package

on:
  release:
    types: [published]
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  buildType: Release
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
      
      - name: Parse version from tag
        id: parse_version
        run: |
          $tag = "${{ github.ref_name }}"
          $major = 0
          $minor = 0
          $patch = 0
          $build = 0
          if ($tag -match "v(\d+)\.(\d+)\.(\d+)\.(\d+)") {
            $major = $matches[1]
            $minor = $matches[2]
            $patch = $matches[3]
            $build = $matches[4]
          }
          echo "##[set-output name=major;]$major"
          echo "##[set-output name=minor;]$minor"
          echo "##[set-output name=patch;]$patch"
          echo "##[set-output name=build;]$build"
        shell: pwsh

      - name: Update Solution Version
        id: update_version
        run: |
          $version = "${{ steps.parse_version.outputs.major }}.${{ steps.parse_version.outputs.minor }}.${{ steps.parse_version.outputs.patch }}.${{ steps.parse_version.outputs.build }}"
          Write-Host "##[set-output name=version;]$version"
          Write-Host "Current version: $version"
          $xml = [xml](Get-Content package/other/Solution.xml)
          $xml.ImportExportXml.SolutionManifest.Version = $version
          $xml.Save("package/other/Solution.xml")
        shell: pwsh

      - name: Get Solution Unique Name
        id: solution-unique-name
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: package/Other/Solution.xml
          xpath: "//ImportExportXml/SolutionManifest/UniqueName"

      - name: Get Solution Version
        id: solution-version
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: package/Other/Solution.xml
          xpath: "//ImportExportXml/SolutionManifest/Version"

      - name: Pack solution as Managed
        uses: microsoft/powerplatform-actions/pack-solution@v1
        env: 
          fileName: "${{ steps.solution-unique-name.outputs.info }}_${{ steps.solution-version.outputs.info }}_managed.zip"
        with:
          solution-file: "./build/${{ env.fileName }}"
          solution-folder: "./package"
          solution-type: "Managed"

      - name: Pack solution as Unmanaged
        uses: microsoft/powerplatform-actions/pack-solution@v1
        env: 
          fileName: "${{ steps.solution-unique-name.outputs.info }}_${{ steps.solution-version.outputs.info }}.zip"
        with:
          solution-file: "./build/${{ env.fileName }}"
          solution-folder: "./package"
          solution-type: "Unmanaged"

      - name: Upload Managed solution to release
        uses: actions/upload-release-asset@v1
        env: 
          fileName: "${{ steps.solution-unique-name.outputs.info }}_${{ steps.solution-version.outputs.info }}_managed.zip"
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./build/${{ env.fileName}}"
          asset_name: ${{ env.fileName}}
          asset_content_type: application/zip

      - name: Upload Unnmanaged solution to release
        uses: actions/upload-release-asset@v1
        env: 
          fileName: "${{ steps.solution-unique-name.outputs.info }}_${{ steps.solution-version.outputs.info }}.zip"
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./build/${{ env.fileName}}"
          asset_name: ${{ env.fileName}}
          asset_content_type: application/zip